---
title: "Untitled"
author: "Agustin Huczok"
date: "7/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)


iteracion_punto_fijo<-function(func,p0,tol,N){
  i<-1
  while(i<=N){
    p=func(p0)
    if(abs(p-p0) < tol){
      return(p)
    }
    i<-i+1
    p0=p
  }
  paste('El metodo fallo despues de ',N,'iteraciones')
}
```


```{r}
f <- function(x){
  log(2+cos(exp(x)-2))
}
#La funci칩n para graficar la raiz
g <- function(x){
  log(2+cos(exp(x)-2))-x
}
```

```{r}

x <- seq(-2, 2, by = 0.0001) #Genero vector para graficar
fx <- f(x)
df <- data.frame(x, fx) #Creo dataframe
gggx <- ggplot(data = df) #Cargo los datos
gggx <- gggx + aes(x = x, y = fx) #Cargo las variables
gggx <- gggx + geom_line(linetype = 1, colour = "darkblue")
#Gr치fico x = y
gggx <- gggx + geom_line(aes(y = x),linetype=4, colour = "black")
#Gr치fico la funci칩n del ejercicio donde esta la raiz
gggx <- gggx + geom_line(aes(x = x, y = g(x)), colour = "green")
#Agrego el eje X e Y
gggx <- gggx + geom_vline(xintercept = 0, linetype = 1)+
   geom_hline(yintercept = 0, linetype = 1)
#Mapeo las escalas
gggx=gggx+scale_x_continuous(name="x",breaks=seq(-2,5,0.5)) +scale_y_continuous(name="y=f(x)",breaks=seq(-2,5,0.5)) +geom_abline(slope=1,intercept = 0,col="red")
gggx
```

Calculo el punto fijo y verifico graficamente que coincida con la raiz

```{r}
gggx=gggx+geom_vline(xintercept=iteracion_punto_fijo(f,1,0.01,300),linetype=1,size=1,colour="darkgreen")+geom_point(aes(x=iteracion_punto_fijo(f,1,0.01,300),y=g(iteracion_punto_fijo(f,1,0.01,300))),pch=10,size=5,col="red")
gggx
```

```{r}
iteracion_punto_fijo(f,1,0.001,100)
```

