---
title: "Factorizacion LU"
author: "Agustin Huczok"
date: "17/9/2021"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
LU <- function(matriz_coeficientes){
  n_incognitas = nrow(matriz_coeficientes)
  
  L <- matrix(rep(0, times = n_incognitas^2), nrow = n_incognitas, ncol = n_incognitas, byrow = TRUE)
  U <- matrix(rep(0, times = n_incognitas^2), nrow = n_incognitas, ncol = n_incognitas, byrow = TRUE)
  
  #Paso 1  -------- 
  for (i in 1:(n_incognitas-1)) {
    #Completo con 1 la diagonal principal de L.
    L[i,i] <- 1
    
    for (j in (i+1):n_incognitas) {
      L[i,j] <- 0
    }
  }
  
  #El último lo completo a mano
  L[n_incognitas, n_incognitas] <- 1
  
  U[1,1] <- matriz_coeficientes[1,1]
  
  
  if(U[1,1] == 0){
    return("factorizacion imposible")
  }
  
  # Paso 2 -------
  
  for (j in 2:n_incognitas) {
    U[1,j] <- matriz_coeficientes[1,j]
    L[j,1] <- matriz_coeficientes[j,1]/U[1,1]
  }
  
  
  # Paso 3 -----------
  
  for(i in 2:(n_incognitas-1)){
    
    # Paso 4 --------
    suma <- 0
    for (k in 1:(i-1)) {
      suma <- suma + L[i,k]*U[k,i]
    }
    
    U[i,i] <- matriz_coeficientes[i,i] - suma
    
    
    if(U[i,i] == 0){
      return("factorizacion imposible")
    }
    
    # Paso 5-----
    
    for (j in (i+1):n_incognitas) {
      sumaU <- 0
      sumaL <- 0
      for (k in 1:(i-1)) {
        sumaU <- sumaU + L[i,k]*U[k,j]
        sumaL <- sumaL + L[j,k]*U[k,i]
      }
      
      U[i,j] <- (1/L[i,i])* (matriz_coeficientes[i,j] - sumaU)
      L[j,i] <- (1/U[i,i])* (matriz_coeficientes[j,i] - sumaL)
      
    }
    
    
  }
  
  
  # Paso 6---------
  
  
  suma <- 0
  for (k in 1:(n_incognitas-1)) {
    suma <- suma + L[n_incognitas,k]*U[k,n_incognitas]
  }
  U[n_incognitas, n_incognitas] <- matriz_coeficientes[n_incognitas,n_incognitas] - suma
  
  
  # Paso 7------
  return(list("L" = L, "U" = U))
}

A <- matrix(c(1,1,0,3,
              2,1,-1,1,
              3,-1,-1,2,
              -1,2,3,-1), nrow = 4, ncol = 4, byrow = TRUE)
LU(matriz_coeficientes = A)
L <- LU(A)$L
U <- LU(A)$U
L%*%U
```
