---
title: "Graficar"
author: "Agustin Huczok"
date: "1/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)

graphics.off()

f=function(x){
  exp(10/x)-2*sin(x)
}


x<-seq(10,30,0.1)#Genero vector para graficar f(x)

fx<-f(x)

df<-data.frame(x,fx) #Creo dataframe

ggfx=ggplot(data=df) #cargo los datos

ggfx=ggfx+aes(x=x,y=fx)#Cargo variables

ggfx=ggfx+geom_line(linetype=1,colour="darkblue") #Agrego linea

ggfx=ggfx+geom_hline(yintercept=0,linetype=1)+geom_vline(xintercept = 0,linetype=1)#Creo x=0 e y=0

ggfx=ggfx+scale_x_continuous(name="x",breaks=seq(0,30,1)) #cambio escala eje X


ggfx=ggfx+geom_vline(xintercept=c(19.5,20.2),linetype=2,colour="red")+geom_vline(xintercept=c(20.6,22),linetype=2,colour="blue")+geom_vline(xintercept=c(25.5,26),linetype=2,colour="orange")+geom_vline(xintercept=c(27,28),linetype=2,colour="green")
ggfx=ggfx+ggtitle("Funcion con 4 raices") #Agrego titulo

ggfx
```

#Linea 45°

geom_abline(slope=1,intercept = 0,col="red")

#Mapeo los ejes en la misma escala


scale_x_continuous(limits = c(0,10))+scale_y_continuous(limits = c(0,10))




#Graficar punto fijo
```{r}
f <- function(x){
  return((10/(4+x))^(1/2))
}
#La función para graficar la raiz
g <- function(x){
  return(-x+(10/(4+x))^(1/2))
}
```

```{r}
x <- seq(0, 2, by = 0.0001) #Genero vector para graficar
fx <- f(x)
df <- data.frame(x, fx) #Creo dataframe
gggx <- ggplot(data = df) #Cargo los datos
gggx <- gggx + aes(x = x, y = fx) #Cargo las variables
gggx <- gggx + geom_line(linetype = 1, colour = "darkblue")
#Gráfico x = y
gggx <- gggx + geom_line(aes(y = x),linetype=4, colour = "black")
#Gráfico la función del ejercicio donde esta la raiz
gggx <- gggx + geom_line(aes(x = x, y = g(x)), colour = "green")
#Agrego el eje X e Y
gggx <- gggx + geom_vline(xintercept = 0, linetype = 1)+
   geom_hline(yintercept = 0, linetype = 1)
#Mapeo las escalas
ggfx=ggfx+scale_x_continuous(name="x",breaks=seq(0,3,0.5)) +scale_y_continuous(name="y=f(x)",breaks=seq(0,3,0.5)) 

gggx
```

Calculo el punto fijo y verifico graficamente que coincida con la raiz

```{r}
gggx=gggx+geom_vline(xintercept=iteracion_punto_fijo(f,1.5,0.01,300),linetype=1,size=1,colour="darkgreen")+geom_point(aes(x=iteracion_punto_fijo(f,1.5,0.01,300),y=g(iteracion_punto_fijo(f,1.5,0.01,300))),pch=10,size=5,col="red")

gggx


```

